### ISSUE TITLE
question about styling

### ISSUE THREAD

**Issue by diomed** [getgrav/grav-theme-striped#4]
hi

I'd like to ask you something about styling of template.
How would I achieve the look of text in subtitle [A free fully responsible HTML site template...]
in my posts.  I'd like posts to be styled as these letters are.

**Comment by hexplor** [comment]
Open css/main.css and at the same bottom add:

``` css
.box.post p {
font-size: 2.25em;
line-height: 1.5em;
position: relative;
font-family: 'Open Sans Condensed', sans-serif;
font-weight: 300;
display: block;
color: #999;
}
```

That should do it :)
